# The URL the site will be built for
base_url = "https://dmarcoux.com" # This isn't actually used, since `zola serve` overwrites it development, and I call `zola build --base-url ...` in preview/production environments

# The site title and description; used in feeds by default.
title = "Dany Marcoux"
description = """\
                Software and DevOps engineer with 12+ years of experience. \
                I write about web development, DevOps, Ruby, Elixir and more.\
              """

# Whether to automatically compile all Sass files in the sass directory
compile_sass = true

# Whether to build a search index to be used later on by a JavaScript library
build_search_index = false

# The generated HTML files are minified.
minify_html = false

# The default language; used in feeds.
default_language = "en"

# The default author for pages
author = "Dany Marcoux"

# Generate RSS and Atom feeds
generate_feeds = true
feed_filenames = ["rss.xml", "atom.xml"]

[markdown]
# Whether to do syntax highlighting
# https://www.getzola.org/documentation/content/syntax-highlighting/
highlight_code = true
highlight_theme = "dracula"

[extra]
menu = [
    { name = "Posts", url = "posts", weight = 1 },
    # TODO: { name = "About", url = "about", weight = 2 },
]

socials = [
    { name = "GitHub", url = "https://github.com/dmarcoux/", icon = "github" },
    { name = "LinkedIn", url = "https://www.linkedin.com/in/danymarcoux/", icon = "linkedin" },
]

custom_css = []
