# TODO: This file is ignored... see https://github.com/dmarcoux/dmarcoux.com/pull/65
name = "dmarcoux-com"
pages_build_output_dir = "public"
compatibility_date = "2024-08-31"

[vars]
ZOLA_VERSION = "0.19.2"

[env.production.vars]
CF_PAGES_URL = "https://dmarcoux.com"
